version: "2"

services:
  nginx:
    build:
      context: ./build
      dockerfile: nginx.dockerfile
    container_name: dev.nginx
    ports: 
      - "7777:7777"
      - "5555:5555"
    links:
      - php7
    volumes_from:
      - data
  php7:
    build:
      context: ./build
      dockerfile: php7.dockerfile
    container_name: dev.php7
    volumes_from:
      - data
  php5:
    build:
      context: ./build
      dockerfile: php5.dockerfile
    container_name: dev.php5
    volumes_from:
      - data
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mkgdb
      - MYSQL_USER=mkd
      - MYSQL_PASSWORD=password
    container_name: dev.db
    ports:
      - "3306:3306"
    volumes_from:
      - data
  # hhvm:
    # build:
    #   context: ./build
    #   dockerfile: hhvm.dockerfile
    # image: hhvm/hhvm:latest
  data:
    image: nginx:1.12-alpine
    volumes:
      - /Users/thevinh/www:/var/www/html:cached
